"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import React, { useEffect } from "react";
import { gsap } from "gsap";
import { ScrollToPlugin } from "gsap/ScrollToPlugin";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const pop = Poppins({ subsets: ["latin"], weight:["200","300","500","600"] });

gsap.registerPlugin(ScrollToPlugin);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scrollbar-thumb-gray-300 scrollbar-thin ">
      <body className={`bg-white overflow-x-hidden ${pop.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
