import Navbar from "@/components/Navbar";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="scrollbar-thumb-gray-300 scrollbar-thin"
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
