"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import React, { useEffect } from "react";
import { gsap } from "gsap";
import { ScrollToPlugin } from "gsap/ScrollToPlugin";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({subsets:['latin']})

gsap.registerPlugin(ScrollToPlugin);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="scrollbar-thumb-gray-300 scrollbar-thin overscroll-none"
    >
      <body className={`container ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
